# Generated by Django 4.2.7 on 2023-12-02 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pawsBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('breed', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('age_unit', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('gender', models.CharField(max_length=50)),
                ('images', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
