# Generated by Django 4.2.7 on 2023-12-03 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pawsBackend', '0004_adoptionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionapplication',
            name='dog',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pawsBackend.doglisting'),
            preserve_default=False,
        ),
    ]
