# Generated by Django 4.2.7 on 2023-12-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawsBackend', '0007_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
